### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by kousu** [sdiehl/numpile#3]
I'm super super fascinated to explore this, and try out the `@autojit` decorator, but llvmpy has [been deprecated](https://github.com/llvmpy/llvmpy/commit/13130fe35f1fb03a7051ad46c36146002391a6fa#diff-88b99bb28683bd5b7e3a204826ead112) in favour of [llvmlite](https://github.com/numba/llvmlite).

I'm installing on OS X but via [brew](https://brew.sh/)+pip instead of Anaconda just because I have been building the rest of my software on this machine against those versions and I'm in too deep to switch to Anaconda just to experiment.

Here's how I installed python:

```
$ brew install python

# add the suggested line to ~/.bash_profile
---------------------------------------------------------------
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
----------------------------------------------------------------
```

Trying to install llvmpy fails for me with

```
ip-192-168-2-145:src kousu$ pip install llvmpy
Collecting llvmpy
  Using cached https://files.pythonhosted.org/packages/97/0f/98b78dc8a5ec032e05179fc406622e550d5c571f036beca8f06a4752f648/llvmpy-0.12.7.tar.gz
    Complete output from command python setup.py egg_info:
    LLVM version = '6.0.1'
    LLVM targets =
    Generate intrinsic IDs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sy/qyp_73v51_757c_h339_h9xw0000gn/T/pip-install-_1kua0qb/llvmpy/setup.py", line 83, in <module>
        auto_intrinsic_gen(incdir)
      File "/private/var/folders/sy/qyp_73v51_757c_h339_h9xw0000gn/T/pip-install-_1kua0qb/llvmpy/setup.py", line 76, in auto_intrinsic_gen
        intrgen.gen(path, fout)
      File "/private/var/folders/sy/qyp_73v51_757c_h339_h9xw0000gn/T/pip-install-_1kua0qb/llvmpy/tools/intrgen.py", line 13, in gen
        for line in open(f):
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/llvm@6/6.0.1/include/llvm/Intrinsics.gen'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sy/qyp_73v51_757c_h339_h9xw0000gn/T/pip-install-_1kua0qb/llvmpy/
```

I'll try to patch numpile to run against llvmlite. First, for that, I need to do:

```
$ brew install llvm@6  # llvmlite is only up to date with last-year's llvm
  ~/.bash_profile
----------------------------------------------------------------
export LDFLAGS="-L/usr/local/opt/llvm@6/lib -Wl,-rpath,/usr/local/opt/llvm@6/lib"
export PATH="/usr/local/opt/llvm@6/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm@6/lib"
export CPPFLAGS="-I/usr/local/opt/llvm@6/include"
----------------------------------------------------------------

$ source ~/.bash_profile

$ pip --version
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ pip install numpy
$ pip install llvmlite
```

... TODO ...

**Comment by kousu** [comment]
Fixed by #7.
